name: Release

on:
  push:
    tags:
    - 'v*'
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Setup project environment
        run: make env

      - name: Make the build
        run: make prefab-gui-debug-build
      - name: Compress the build
        run: tar -cf "linux_x86_64_gui(debug).tar" build/prefab/full/linux_x86_64_gui/
      - name: Upload the build
        uses: ncipollo/release-action@v1
        with:
            allowUpdates: true
            artifacts: build/prefab/full/linux_x86_64_gui/*

      - name: Make the build
        run: make prefab-server-debug-build
      - name: Compress the build
        run: tar -cf "linux_x86_64_server(debug).tar" build/prefab/full/linux_x86_64_server/
      - name: Upload the build
        uses: ncipollo/release-action@v1
        with:
            allowUpdates: true
            artifacts: linux_x86_64_server(debug).tar